### ISSUE TITLE
Focus handler

### ISSUE THREAD

**Issue by zslabs** [tristen/hoverintent#18]
Hi,
I don't believe the dropdown would be triggered when using keyboards for accessibility, correct? That would focus on something more like `focus` instead of `hover`; looking at the current codebase that doesn't appear to be pluggable; I believe I might be able to bundle ontop of some internal functions to call those methods, but wanted to hear your thoughts. Thanks!

**Comment by tristen** [comment]
Closed by https://github.com/tristen/hoverintent/pull/25
