### ISSUE TITLE
Buggy behavior when mouse moves at corner

### ISSUE THREAD

**Issue by steelbrain** [tristen/hoverintent#20]
This is from your demo page

![kapture 2017-02-02 at 4 44 03](https://cloud.githubusercontent.com/assets/4278113/22531383/50772062-e902-11e6-87de-7500c3eef8fe.gif)

**Comment by tristen** [comment]
This isn't really a bug. The hover state is active when the cursor is over the element and it's being animated back over the cursor when you come off the edge of it. I can remove the tooltip animation if it's causing confusion!

**Comment by steelbrain** [comment]
Yeah IMHO the behavior in the gif should not be the intended behavior. That gif isn't even sped up, it makes weird movement when cursor is near the end of tooltip area

**Comment by tristen** [comment]
I understand but it's not an issue with hoverintent. It's an issue with the CSS animation used in the example. I can remove it 👍
