### ISSUE TITLE
Misleading description

### ISSUE THREAD

**Issue by Solant** [tristen/hoverintent#23]
I'm greatly insulted with the fact that "It has no dependencies" statement is actually a lie. Please, remove it from the description.
![screenshot_20180323_135929](https://user-images.githubusercontent.com/5971578/37826324-d3e4ad74-2e8a-11e8-89d9-3f0da95e7206.png)

**Comment by austinpray** [comment]
Brother if you are so insulted why not just make a PR to remove the dep?

**Comment by Solant** [comment]
@austinpray thats actually a good idea. Feel free to comment or ask anything on PR.

**Comment by tristen** [comment]
Closed by https://github.com/tristen/hoverintent/pull/24
