### ISSUE TITLE
Add cjs support

### ISSUE THREAD

**Issue by olsonpm** [tristen/hoverintent#7]
Please provide 'require()' support for cjs.  Personally I don't have a need for any other modules, but it would probably help others to just add umd support.

I can create a pull request if you respond to this.  Otherwise I'll just publish a fork to npm.

**Comment by tristen** [comment]
@olsonpm a pull request would be great!

**Comment by olsonpm** [comment]
Awesome. I'll have one by tomorrow, not sure i'll get to it tonight.

**Comment by olsonpm** [comment]
Hey so I finally finished up a couple personal projects and had time to look into this.  The deal-breaking issue I realize is that you want hoverintent to be attached to the window as opposed to the jquery object.  I wanted to keep this as a jquery plugin, and don't want to mess with your library's assumption of having the global context.  I'll just keep a personal copy then.

Sorry for the bother!  And sorry it took me so long to get back to this.
